"""added a relationship

Revision ID: 068e33ca2e01
Revises: a013a07ec196
Create Date: 2023-09-21 17:05:21.040803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068e33ca2e01'
down_revision = 'a013a07ec196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.drop_column('stats', 'user_id')
    # ### end Alembic commands ###
