"""hamstring typo

Revision ID: 78edc4fbef3a
Revises: a630b20ef4c3
Create Date: 2023-09-22 20:55:28.279630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78edc4fbef3a'
down_revision = 'a630b20ef4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hamstrings', sa.Integer(), nullable=True))
        batch_op.drop_column('hamgstrings')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hamgstrings', sa.INTEGER(), nullable=True))
        batch_op.drop_column('hamstrings')

    # ### end Alembic commands ###
