"""all tables created

Revision ID: be4cb0495b24
Revises: e57e9fc882e0
Create Date: 2023-09-18 18:58:36.874300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4cb0495b24'
down_revision = 'e57e9fc882e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('stats', sa.Column('chest', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('back', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('legs', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('arms', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('core', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'core')
    op.drop_column('stats', 'arms')
    op.drop_column('stats', 'legs')
    op.drop_column('stats', 'back')
    op.drop_column('stats', 'chest')
    op.drop_table('excercises')
    # ### end Alembic commands ###
