"""all tables

Revision ID: e57e9fc882e0
Revises: 55c977bf79ae
Create Date: 2023-09-18 18:52:55.375179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57e9fc882e0'
down_revision = '55c977bf79ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
