"""create tables

Revision ID: f1184684fc41
Revises: 
Create Date: 2023-09-22 17:24:37.591508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1184684fc41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('name', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chest', sa.Integer(), nullable=True),
    sa.Column('lats', sa.Integer(), nullable=True),
    sa.Column('triceps', sa.Integer(), nullable=True),
    sa.Column('biceps', sa.Integer(), nullable=True),
    sa.Column('abdominals', sa.Integer(), nullable=True),
    sa.Column('quadriceps', sa.Integer(), nullable=True),
    sa.Column('hangstrings', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    op.drop_table('users')
    op.drop_table('excercises')
    # ### end Alembic commands ###
